[tool.poetry]
name = "Nexus Service"
version = "0.1.0"
description = "A helper for the Nexus API developed by Tycho Systems."

[tool.poetry.dependencies]
python = ">=3.8"
aiohttp = "*"
pydantic = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
